# api: apps/v1 
# kind: Service 
# metadata: 
#   name: chatbot-service 
#   namespace: chatbot
# spec: 
#   type: nodePort
# selector: 
#   app: chatbot
# ports: 
#   - name: http 
#     protocol: TCP 
#     port: 80 
#     targetPort: 8080 
#     nodePort: 30036


apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: chatbot
spec:
  type: NodePort
  selector:
    app: chatbot
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30036

